# Generated by Django 4.1.7 on 2023-03-26 22:35

from django.db import migrations, models


def split_name(apps, schema_editor):
    teamuser_model = apps.get_model("users", "TeamUser")
    for user in teamuser_model.objects.all():
        if user.name:
            if " " in user.name:
                user.first_name, user.last_name = user.name.split(maxsplit=1)
            else:
                user.first_name = user.name
            user.save()


def combine_name(apps, schema_editor):
    teamuser_model = apps.get_model("users", "TeamUser")
    for user in teamuser_model.objects.all():
        user.name = f"{user.first_name} {user.last_name}".strip()
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_initial_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="teamuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.RunPython(split_name, reverse_code=combine_name),
        migrations.RemoveField(
            model_name="teamuser",
            name="name",
        ),
    ]
