# Generated by Django 4.1.6 on 2023-02-12 01:27

import address.models
import django.db.models.deletion
import django.utils.translation
import django_quill.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    # noinspection SpellCheckingInspection
    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="contact email"
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=254, verbose_name="contact name"
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="contact phone"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=254, verbose_name="area name"),
        ),
        migrations.AlterField(
            model_name="area",
            name="state",
            field=models.CharField(
                choices=[
                    ("ACT", "Australian Capital Territory"),
                    ("NSW", "New South Wales"),
                    ("NT", "Northern Territory"),
                    ("QLD", "Queensland"),
                    ("SA", "South Australia"),
                    ("TAS", "Tasmania"),
                    ("VIC", "Victoria"),
                    ("WA", "Western Australia"),
                ],
                max_length=3,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="address.address",
                verbose_name="address",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="api.area",
                verbose_name="area",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(max_length=254, verbose_name="business name"),
        ),
        migrations.AlterField(
            model_name="business",
            name="owners",
            field=models.ManyToManyField(
                related_name="owned_businesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owners",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="name",
            field=models.CharField(max_length=254, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="state",
            field=models.CharField(
                choices=[
                    ("ACT", "Australian Capital Territory"),
                    ("NSW", "New South Wales"),
                    ("NT", "Northern Territory"),
                    ("QLD", "Queensland"),
                    ("SA", "South Australia"),
                    ("TAS", "Tasmania"),
                    ("VIC", "Victoria"),
                    ("WA", "Western Australia"),
                ],
                max_length=3,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="listing_expiry",
            field=models.DateTimeField(verbose_name="listing expiry"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=254, verbose_name="area name"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cv",
            field=models.FileField(upload_to="uploads/", verbose_name="cv"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="experience",
            field=models.TextField(verbose_name="experience"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="first_name",
            field=models.CharField(max_length=254, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job_listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="api.joblisting",
                verbose_name="job listing",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="last_name",
            field=models.CharField(max_length=254, verbose_name="last_name"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="mobile"
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_listins",
                to="api.business",
                verbose_name="business",
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_listings",
                to="api.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="certificates_required",
            field=models.ManyToManyField(
                related_name="joblistings",
                to="api.certificate",
                verbose_name="certificates required",
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="description",
            field=django_quill.fields.QuillField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="listing_expiry",
            field=models.DateTimeField(verbose_name="listing expiry"),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="title",
            field=models.CharField(
                blank=True, max_length=254, verbose_name="job title"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="contact",
            field=models.ForeignKey(
                help_text="Primary contact for the business",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="owners",
            field=models.ManyToManyField(
                help_text="Users with administrative access to the business",
                related_name="owned_businesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owners",
            ),
        ),
    ]
