# Generated by Django 4.1.6 on 2023-02-12 01:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_add_verbose_names_add_contact_joblisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="listing_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="listing create at",
            ),
            preserve_default=False,
        ),
    ]
