# Generated by Django 4.1.7 on 2023-02-23 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_category_options_area_api_area_state_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_listings",
                to="api.business",
                verbose_name="business",
            ),
        ),
    ]
