# Generated by Django 4.1.7 on 2023-02-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_category_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.UniqueConstraint(
                fields=("name", "state"), name="api_certificate_unique_name_state"
            ),
        ),
    ]
