# Generated by Django 4.1.7 on 2023-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_certificate_api_certificate_unique_name_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("P", "Permanent"),
                    ("C", "Casual"),
                    ("S", "Shifts"),
                    ("", "Unspecified"),
                ],
                default="",
                max_length=1,
                verbose_name="job type",
            ),
        ),
    ]
