# Generated by Django 4.1.7 on 2023-02-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_joblisting_job_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblisting",
            name="job_type",
        ),
        migrations.AddField(
            model_name="joblisting",
            name="position_type",
            field=models.CharField(
                choices=[
                    ("P", "Permanent"),
                    ("C", "Casual"),
                    ("S", "Shifts"),
                    ("", "Unspecified"),
                ],
                default="",
                max_length=1,
                verbose_name="position type",
            ),
        ),
    ]
