# Generated by Django 4.1.7 on 2023-03-15 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_area_options_alter_business_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["-created"], name="api_jobappl_created_68805f_idx"
            ),
        ),
    ]
