# Generated by Django 4.1.7 on 2023-03-28 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_jobapplication_options_jobapplication_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="address",
            new_name="address_old",
        ),
    ]
