# Generated by Django 4.1.7 on 2023-03-28 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_migrate_business_address_to_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="address_old",
        ),
    ]
