# Generated by Django 4.1.7 on 2023-03-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_remove_business_address_old"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="certificates_required",
            field=models.ManyToManyField(
                blank=True,
                related_name="joblistings",
                to="api.certificate",
                verbose_name="certificates required",
            ),
        ),
    ]
