# Generated by Django 4.1.7 on 2023-03-29 05:05

import api.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_joblisting_certificates_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="description_html",
            field=api.fields.CleanHTMLField(default="", verbose_name="description"),
            preserve_default=False,
        ),
    ]
