# Generated by Django 4.1.7 on 2023-03-29 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_migrate_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblisting",
            name="description",
        ),
    ]
