# Generated by Django 4.1.7 on 2023-03-29 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_remove_joblisting_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joblisting",
            old_name="description_html",
            new_name="description",
        ),
    ]
