# Generated by Django 4.2 on 2023-04-03 16:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_rename_description_html_joblisting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="cv",
            field=models.FileField(
                storage=api.models.get_cv_storage,
                upload_to=api.models.cv_upload_to,
                verbose_name="cv",
            ),
        ),
    ]
